### ISSUE TITLE
Licensing question 

### ISSUE THREAD

**Issue by mirchiseth** [sivaprasadreddy/TrackIT#1]
Hi Siva,

I came to your TrackIT repo while searching for custom spring boot starter. TrackIT looks like a good example of spring boot application. I wanted to port this to use SAP HANA as a database and make few more changes and then run it on our cloud platform as an example application. Before doing that I wanted to make sure that the license is really **Apache 2.0** which is the default for github projects. 

Let me know. Thanks.

Pankaj
http://pnarula.com

**Comment by sivaprasadreddy** [comment]
Hi Pankaj,
I am glad that you liked this repo. It is Apache 2.0  licensed and feel free to use it for your project. All the best.
